name: Kwiki-Theme-Selectable
version: 0.10
abstract: Kwiki Preference to Select a Theme
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
